alias open=xdg-open
alias diskspace="du -S | sort -n -r |more"
alias open=xdg-open
alias folders="find . -maxdepth 1 -type d -print | xargs du -sk | sort -rn"
alias please='sudo $(fc -ln -1)'
alias pc="ssh philipj@desktop.lan"
alias laptop="ssh philipj@laptop.lan"
alias rasp="ssh pi@pi.lan"
alias phone="ssh localhost@phone.lan -p 8022"
alias python="python3"
alias pip="pip3"
alias co="cd ~/Documents/Code/"
alias calc="python -i -c 'from math import *; import numpy as np;'"
alias vimsu="sudo -E vim"
