alias open=xdg-open
alias tor="sh -c '\"/home/philipj/tor-browser_en-US/Browser/start-tor-browser\" --detach || ([ !  -x \"/home/philipj/tor-browser_en-US/Browser/start-tor-browser\" ] && \"$(dirname \"$*\")\"/Browser/start-tor-browser --detach)' dummy %k"
alias diskspace="du -S | sort -n -r |more"
alias open=xdg-open
alias folders="find . -maxdepth 1 -type d -print | xargs du -sk | sort -rn"
alias please='sudo $(fc -ln -1)'
alias rm='echo "Are you sure you want to use this command? Did you mean trash-put?"; echo "If you meant to use rm type \\\\rm"; false'
alias pc="ssh philipj@192.168.0.21"
alias laptop="ssh philipj@192.168.0.43"
alias phone="ssh 192.168.0.18 -p 8022"
alias python="python3"
alias pip="pip3"
alias co="cd ~/Documents/Code/"
alias calc="python -i -c 'from math import *; import numpy as np;'"
alias vimsu="sudo -E vim"
alias nnn="tmux new-session 'zsh -c \"nnn -edDxaP p\"'"
