set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mode-keys vi
set -g mouse on
set -g status-keys vi
set -g base-index 1
setw -g pane-base-index 1
set -g default-terminal "screen-256color"
setw -g monitor-activity on
set -g visual-activity on
setw -g automatic-rename on
set -g renumber-windows on
set -g set-titles on
setw -g aggresive-resize on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'arcticicestudio/nord-tmux'
set -g @plugin 'tmux-plugins/tmux-sessionist'

run-shell '~/.config/tmux/plugins/tmux-yank/yank.tmux'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
