alias open=xdg-open
alias diskspace="du -S | sort -n -r | less"
alias folders="find . -maxdepth 1 -type d -print | xargs du -sk | sort -rn"
alias rm='echo "Are you sure you want to use this command? Did you mean trash-put?"; echo "If you meant to use rm type \\\\rm"; false'
alias loki="ssh -X philipj@loki.asgard"
alias balder="ssh -X philipj@balder.asgard"
alias heimdall="ssh -X pi@heimdall.asgard"
alias phone="ssh localhost@phone.lan -p 8022"
alias python="python3"
alias pip="pip3"
alias calc="python -i -c 'from math import *; import numpy as np;'"
alias vimsu="sudo -e"
alias -s pdf=zathura
alias gpg2=gpg2 --homedir "$XDG_DATA_HOME"/gnupg
alias dragon="dragon-drag-and-drop -a -x"
alias lf="lfrun || lf"
